# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be7cd5d7c64ab59fa266769b743e845b93db4060ac6ad2193fe0da83a7360c44e6f9aa780491dfc95650b9ab33252a756db7bf40cb98b45708db0f98c26d8fc8

test:
  secret_key_base: 48b194cfd9b7ed0e4f193f93f244dc83fede526b4a7338e3f3f0ec2a446b56c27ef7537864cfbf513f79080cb54eff6b9754049bb5d1a1339053b26a4684a5e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
